### ISSUE TITLE
Reindex not working

### ISSUE THREAD

**Issue by pradhakrishnan** [garbin/elasticsearch-reindex#14]
Hi,

I have tried to create new index from my existing index. Below is the output

```
> elasticsearch-reindex -f http://127.0.0.1:9200/customer/external -t http://127.0.0.1:9200/

Starting reindex in 1 shards.
 reindexing [==============================] 1/1(100%) 0.0 0.0s - 1/1 working
Reindexing completed sucessfully.
```

But the new mappings are not applied in my new index files.

Can some one help me on this.

**Comment by MagRelo** [comment]
Hi,

I'm not totally sure on this, but I don't see anything in the code to handle mapping; I am manually PUT'ing my new mapping into ES, and then running this lib to do the re-indexing only. It's working great for me so far.

**Comment by chrishiestand** [comment]
Yes, you have to do the mapping first - then re-index.

**Comment by garbin** [comment]
I've merged #16,  Can I close this issue?

**Comment by chrishiestand** [comment]
I'm not the OP but I think this was an invalid issue and should be closed.

**Comment by garbin** [comment]
Thank you @chrishiestand
