### ISSUE TITLE
Fails to reindex documents that have parents

### ISSUE THREAD

**Issue by brooksrbrown** [garbin/elasticsearch-reindex#5]
If you set up a parent-child relationship between documents, the child documents fail to be reindexed.

PUT /company
{
  "mappings": {
    "branch": {},
    "employee": {
      "_parent": {
        "type": "branch" 
      }
    }
  }
}

In this case, any employee documents will not be reindexed.

**Comment by garbin** [comment]
see https://github.com/garbin/elasticsearch-reindex/pull/3 , I think you should pass `-p ParentField` instead.
